name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build_ios_app:
    name: Build iOS App
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2.4.0
        with:
          java-version: 1.8
          distribution: adopt
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          java-version: 8
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8

      - name: Build
        run: |
          ionic cordova build ios --prod
